# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_squashed_0003_organization_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
