# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
